steps:
  - name: "gcr.io/cloud-builders/npm:current"
    args:
      ["ci"]
  # デプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "functions",
      "deploy",
      "${_FUNCTION_NAME}",
      "--gen2",
      "--trigger-topic",
      "${_TOPIC_ID}",
      "--region=asia-northeast1",
      "--source=.",
      "--entry-point=helloPubSub"
    ]

options:
  logging: "CLOUD_LOGGING_ONLY"
